<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="NetTcpBinding_IChatService_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <msb:BinaryEncoding xmlns:msb="http://schemas.microsoft.com/ws/06/2004/mspolicy/netbinary1" />
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <msf:WindowsTransportSecurity xmlns:msf="http://schemas.microsoft.com/ws/2006/05/framing/policy">
                  <msf:ProtectionLevel>EncryptAndSign</msf:ProtectionLevel>
                </msf:WindowsTransportSecurity>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import namespace="http://tempuri.org/" />
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/Andead.Chat.Server" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IChatService_SignIn_InputMessage">
    <wsdl:part name="parameters" element="tns:SignIn" />
  </wsdl:message>
  <wsdl:message name="IChatService_SignIn_OutputMessage">
    <wsdl:part name="parameters" element="tns:SignInResponse" />
  </wsdl:message>
  <wsdl:message name="IChatService_SignOut_InputMessage">
    <wsdl:part name="parameters" element="tns:SignOut" />
  </wsdl:message>
  <wsdl:message name="IChatService_SignOut_OutputMessage">
    <wsdl:part name="parameters" element="tns:SignOutResponse" />
  </wsdl:message>
  <wsdl:message name="IChatService_SendMessage_InputMessage">
    <wsdl:part name="parameters" element="tns:SendMessage" />
  </wsdl:message>
  <wsdl:message name="IChatService_ReceiveMessage_OutputCallbackMessage">
    <wsdl:part name="parameters" element="tns:ReceiveMessage" />
  </wsdl:message>
  <wsdl:portType name="IChatService">
    <wsdl:operation name="SignIn">
      <wsdl:input wsaw:Action="http://tempuri.org/IChatService/SignIn" message="tns:IChatService_SignIn_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IChatService/SignInResponse" message="tns:IChatService_SignIn_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="SignOut">
      <wsdl:input wsaw:Action="http://tempuri.org/IChatService/SignOut" message="tns:IChatService_SignOut_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IChatService/SignOutResponse" message="tns:IChatService_SignOut_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="SendMessage">
      <wsdl:input wsaw:Action="http://tempuri.org/IChatService/SendMessage" message="tns:IChatService_SendMessage_InputMessage" />
    </wsdl:operation>
    <wsdl:operation name="ReceiveMessage">
      <wsdl:output wsaw:Action="http://tempuri.org/IChatService/ReceiveMessage" message="tns:IChatService_ReceiveMessage_OutputCallbackMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NetTcpBinding_IChatService" type="tns:IChatService">
    <wsp:PolicyReference URI="#NetTcpBinding_IChatService_policy" />
    <soap12:binding transport="http://schemas.microsoft.com/soap/tcp" />
    <wsdl:operation name="SignIn">
      <soap12:operation soapAction="http://tempuri.org/IChatService/SignIn" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SignOut">
      <soap12:operation soapAction="http://tempuri.org/IChatService/SignOut" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SendMessage">
      <soap12:operation soapAction="http://tempuri.org/IChatService/SendMessage" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="ReceiveMessage">
      <soap12:operation soapAction="http://tempuri.org/IChatService/ReceiveMessage" style="document" />
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service">
    <wsdl:port name="NetTcpBinding_IChatService" binding="tns:NetTcpBinding_IChatService">
      <soap12:address location="net.tcp://localhost/Chat/" />
      <wsa10:EndpointReference>
        <wsa10:Address>net.tcp://localhost/Chat/</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Upn>ANDREW-PC\Andead</Upn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>